### ISSUE TITLE
Error in build_zfs()

### ISSUE THREAD

**Issue by caewok** [Salamandar/armbian_zfs_compiler#1]
My setup: Linux helios64 5.10.16-rockchip64 #21.02.2 SMP PREEMPT Sun Feb 14 21:35:01 CET 2021 aarch64 GNU/Linux
Installing zfs 2.0.3. Debian. 

Pretty sure this line in the function build_zfs() in build_all.sh should be: 
`sudo mv zfs/*.deb "builder_${part}"`

(The `builder` and the `${part}` are flipped in the original.)

Also, worth noting that anyone using the script may have to separately install zfs utils and optionally zfs autosnapshot:
`sudo apt update && sudo apt install zfsutils-linux zfs-auto-snapshot`

With that, this script worked for me. Thanks!

**Comment by Salamandar** [comment]
Yeah, the first point is fixed.

zfs-utils should be generated by this script. I didn't know about zfs-auto-snapshot, thanks ;)

Although, this repository is not necessary anymore : the `zfs-dkms` package in Armbian repositories should be working now !

**Comment by caewok** [comment]
Yeah, zfs-dkms should be working but I could not get it to install correctly!


Sent from Yahoo Mail for iPhone


On Wednesday, February 17, 2021, 01:17, Salamandar <notifications@github.com> wrote:




Yeah, the first point is fixed.

zfs-utils should be generated by this script. I didn't know about zfs-auto-snapshot, thanks ;)

Although, this repository is not necessary anymore : the zfs-dkms package in Armbian repositories should be working now !
